apiVersion: v1
kind: ConfigMap
metadata:
  name: scylla-local-config
  namespace: scylla
data:
  scylla.yaml: |
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    cluster_name: 'scylladb'
    # Other options
