# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: /Users/cong.guo/Project/kind/data/kind-worker-1
      containerPath: /mnt/data
- role: worker
  extraMounts:
    - hostPath: /Users/cong.guo/Project/kind/data/kind-worker-2
      containerPath: /mnt/data
- role: worker
  extraMounts:
    - hostPath: /Users/cong.guo/Project/kind/data/kind-worker-3
      containerPath: /mnt/data
