# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
    - hostPath: ./dataplatform/kind/data/kind-worker-1/scylla
      containerPath: /mnt/data/scylla
    - hostPath: ./dataplatform/kind/data/kind-worker-1/minio
      containerPath: /mnt/data/minio
    - hostPath: ./dataplatform/kind/data/kind-worker-1/iceberg
      containerPath: /mnt/data/iceberg
    - hostPath: ./dataplatform/kind/data/kind-worker-1/kafka
      containerPath: /mnt/data/kafka
    - hostPath: ./dataplatform/kind/data/kind-worker-1/es
      containerPath: /mnt/data/es
    - hostPath: ./dataplatform/kind/data/kind-worker-1/nebula
      containerPath: /mnt/data/nebula
    - hostPath: ./dataplatform/kind/data/kind-worker-1/milvus
      containerPath: /mnt/data/milvus
- role: worker
  extraMounts:
    - hostPath: ./dataplatform/kind/data/kind-worker-2/scylla
      containerPath: /mnt/data/scylla
    - hostPath: ./dataplatform/kind/data/kind-worker-2/minio
      containerPath: /mnt/data/minio
    - hostPath: ./dataplatform/kind/data/kind-worker-2/iceberg
      containerPath: /mnt/data/iceberg
    - hostPath: ./dataplatform/kind/data/kind-worker-2/kafka
      containerPath: /mnt/data/kafka
    - hostPath: ./dataplatform/kind/data/kind-worker-2/es
      containerPath: /mnt/data/es
    - hostPath: ./dataplatform/kind/data/kind-worker-2/nebula
      containerPath: /mnt/data/nebula
    - hostPath: ./dataplatform/kind/data/kind-worker-2/milvus
      containerPath: /mnt/data/milvus
- role: worker
  extraMounts:
    - hostPath: ./dataplatform/kind/data/kind-worker-3/scylla
      containerPath: /mnt/data/scylla
    - hostPath: ./dataplatform/kind/data/kind-worker-3/minio
      containerPath: /mnt/data/minio
    - hostPath: ./dataplatform/kind/data/kind-worker-3/iceberg
      containerPath: /mnt/data/iceberg
    - hostPath: ./dataplatform/kind/data/kind-worker-3/kafka
      containerPath: /mnt/data/kafka
    - hostPath: ./dataplatform/kind/data/kind-worker-3/es
      containerPath: /mnt/data/es
    - hostPath: ./dataplatform/kind/data/kind-worker-3/nebula
      containerPath: /mnt/data/nebula
    - hostPath: ./dataplatform/kind/data/kind-worker-3/milvus
      containerPath: /mnt/data/milvus
