apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-nodes
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-main
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 20Gi
    class: kafka-static-storage # <-- Matches the PV storageClassName perfectly
  resources:
    requests:
      memory: 2Gi
      cpu: "1"
    limits:
      memory: 4Gi
      cpu: "2"
