apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
  labels:
    app: kafka
spec:
  capacity:
    storage: 20Gi
  storageClassName: kafka-static-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-1
  labels:
    app: kafka
spec:
  capacity:
    storage: 20Gi
  storageClassName: kafka-static-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-2
  labels:
    app: kafka
spec:
  capacity:
    storage: 20Gi
  storageClassName: kafka-static-storage
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "3"

