# StorageClass for minio
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath-minio
  namespace: minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-0
  namespace: minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-minio
  hostPath:
    path: /mnt/data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-1
  namespace: minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-minio
  hostPath:
    path: /mnt/data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-2
  namespace: minio
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath-minio
  hostPath:
    path: /mnt/data/minio
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-no
          operator: In
          values:
          - "3"
